import { useEffect, useMemo, useRef, useState } from "react";
import { NavLink } from "react-router-dom";
import { ChevronDown, ChevronRight, FilePlus2, FileText, Folder, FolderOpen, FolderPlus, MoreHorizontal, Pencil, Trash2 } from "lucide-react";
import type { WorkspaceNode } from "../../types/project";
import type { Paper } from "../../types/paper";
import { buildWorkspaceTree } from "../../data/workspace/tree";
import { useProjectStore } from "../../stores/projectStore";
import { showToast } from "../../stores/toastStore";
import { useLibraryCache } from "../../stores/libraryCache";
import { useDraggablePaper } from "../library/useDraggablePaper";
import { useWorkspaceDrag } from "./useWorkspaceDrag";
import { renameWorkspaceItem } from "../../services/projectService";
import styles from "./AppSidebar.module.css";

export function WorkspaceTree({ nodes, activeNodeId, dropTargetId, draggingPaperId, onDelete, onNewChild, onAddPaper }: { nodes: WorkspaceNode[]; activeNodeId?: string | null; dropTargetId?: string | null; draggingPaperId?: string | null; onDelete: (node: WorkspaceNode) => Promise<void>; onNewChild: (node: WorkspaceNode) => void; onAddPaper: (node: WorkspaceNode) => void }) {
  const tree = useMemo(() => buildWorkspaceTree(nodes), [nodes]); const memberships = useProjectStore((state) => state.memberships); const papers = useLibraryCache((state) => state.papers);
  const [collapsed, setCollapsed] = useState<Record<string, boolean>>({}); const [openMenuId, setOpenMenuId] = useState<string | null>(null); const [editingId, setEditingId] = useState<string | null>(null); const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null); const [deleting, setDeleting] = useState(false); const treeRef = useRef<HTMLElement>(null);
  const drag = useWorkspaceDrag(nodes, (id) => { if (id) setCollapsed((current) => ({ ...current, [id]: false })); });
  useEffect(() => { if (!openMenuId) return; const sidebar = treeRef.current?.closest("aside"); const close = () => setOpenMenuId(null); sidebar?.addEventListener("pointerleave", close); window.addEventListener("keydown", (event) => { if (event.key === "Escape") close(); }); return () => sidebar?.removeEventListener("pointerleave", close); }, [openMenuId]);
  const renderNode = (node: ReturnType<typeof buildWorkspaceTree>[number], depth: number) => {
    const isOpen = !collapsed[node.id]; const menuOpen = openMenuId === node.id; const target = drag.drop?.id === node.id ? drag.drop : null;
    const links = memberships.filter((link) => link.nodeId === node.id).sort((a, b) => a.order - b.order);
    const toggle = () => setCollapsed((current) => ({ ...current, [node.id]: !current[node.id] }));
    return <div key={node.id}><div className={`${styles.projectRow} ${styles.treeRow} ${menuOpen ? styles.treeRowMenuOpen : ""} ${target?.error ? styles.invalidDrop : ""} ${target ? styles["drop" + target.edge] : ""} ${dropTargetId === node.id ? styles.dropinside : ""}`} data-workspace-id={node.id} data-project-drop-id={node.id} style={{ "--tree-indent": `${depth * 16}px` } as React.CSSProperties} onPointerDown={(event) => drag.onPointerDown(event, node.id)}>
      <button type="button" className={styles.chevron} aria-label={`${node.name}を${isOpen ? "折りたたむ" : "展開"}`} aria-expanded={isOpen} onClick={toggle}>{isOpen ? <ChevronDown size={14} /> : <ChevronRight size={14} />}</button>
      {editingId === node.id ? <div className={`${styles.item} ${styles.treeLabel}`} data-workspace-editing><span className={styles.icon}>{isOpen ? <FolderOpen size={16} /> : <Folder size={16} />}</span><InlineName node={node} onClose={() => setEditingId(null)} /></div> : <NavLink to={`/project/${node.id}`} draggable={false} className={`${styles.item} ${styles.treeLabel} ${activeNodeId === node.id ? styles.active : ""}`} title={node.name} onClick={(event) => { if (draggingPaperId) event.preventDefault(); setOpenMenuId(null); }}><span className={styles.icon}>{isOpen ? <FolderOpen size={16} /> : <Folder size={16} />}</span><span className={styles.itemLabel}>{node.name}</span></NavLink>}
      <button type="button" className={`${styles.projectMenuButton} ${menuOpen ? styles.projectMenuButtonOpen : ""}`} aria-label={`「${node.name}」のメニュー`} aria-haspopup="menu" aria-expanded={menuOpen} onClick={() => { setOpenMenuId(menuOpen ? null : node.id); setConfirmDeleteId(null); }}><MoreHorizontal size={16} /></button>
      {menuOpen && <div className={styles.projectMenu} role="menu">{confirmDeleteId === node.id ? <><p className={styles.menuNotice}>「{node.name}」と配下の項目を削除しますか？論文ファイルは残ります。</p><button role="menuitem" onClick={() => setConfirmDeleteId(null)}>キャンセル</button><button role="menuitem" className={styles.projectMenuDanger} disabled={deleting} onClick={() => { setDeleting(true); void onDelete(node).then(() => setOpenMenuId(null)).catch((error: unknown) => showToast({ kind: "error", message: error instanceof Error ? error.message : "削除に失敗しました" })).finally(() => setDeleting(false)); }}>{deleting ? "削除中…" : "削除する"}</button></> : <><button role="menuitem" onClick={() => { setOpenMenuId(null); onNewChild(node); setCollapsed((current) => ({ ...current, [node.id]: false })); }}><FolderPlus size={14} />サブフォルダーを追加</button><button role="menuitem" onClick={() => { setOpenMenuId(null); setEditingId(node.id); }}><Pencil size={14} />名称を変更</button><button role="menuitem" onClick={() => { setOpenMenuId(null); onAddPaper(node); }}><FilePlus2 size={14} />論文ファイルを追加</button><div className={styles.projectMenuSeparator} /><button role="menuitem" className={styles.projectMenuDanger} onClick={() => setConfirmDeleteId(node.id)}><Trash2 size={14} />削除</button></>}</div>}
    </div>{isOpen && <div>{node.children.map((child) => renderNode(child, depth + 1))}{links.map((link) => { const paper = papers.find((item) => item.id === link.paperId); return paper ? <PaperItem key={`${node.id}-${paper.id}`} paper={paper} depth={depth + 1} sourceNodeId={node.id} /> : null; })}</div>}</div>;
  };
  return <nav ref={treeRef} className={styles.nav} aria-label="ワークスペース" onClickCapture={drag.onClickCapture}>{tree.length ? tree.map((node) => renderNode(node, 0)) : <p className={`${styles.empty} ${styles.label}`}>フォルダを追加</p>}<div data-workspace-id="root" className={`${styles.rootDrop} ${drag.dragging ? styles.rootDropVisible : ""} ${drag.drop?.id === "root" ? styles.dropinside : ""}`}>ルートへ移動</div></nav>;
}
function PaperItem({ paper, depth, sourceNodeId }: { paper: Paper; depth: number; sourceNodeId: string }) { const label = paper.titleTranslated || paper.titleOriginal || "無題の論文"; const drag = useDraggablePaper(paper.id, label, true, sourceNodeId); return <NavLink to={`/reader/${paper.id}`} title={label} draggable={false} className={`${styles.item} ${styles.treePaper}`} style={{ "--tree-indent": `${depth * 16}px` } as React.CSSProperties} onPointerDown={drag.onPointerDown} onDragStart={(event) => event.preventDefault()} onClick={(event) => { if (drag.consumeClickIfDragged()) event.preventDefault(); }}><span className={styles.icon}><FileText size={14} /></span><span className={styles.itemLabel}>{label}</span></NavLink>; }
function InlineName({ node, onClose }: { node: WorkspaceNode; onClose: () => void }) { const [value, setValue] = useState(node.name); const input = useRef<HTMLInputElement>(null); useEffect(() => { input.current?.focus(); input.current?.select(); }, []); const save = async () => { if (!value.trim()) return; try { await renameWorkspaceItem(node.id, value); useProjectStore.getState().upsertWorkspaceNode({ ...node, name: value.trim() }); onClose(); } catch (error) { showToast({ kind: "error", message: error instanceof Error ? error.message : "変更に失敗しました" }); } }; return <div className={styles.inlineName}><input ref={input} aria-label="名称" value={value} onChange={(event) => setValue(event.target.value)} onPointerDown={(event) => event.stopPropagation()} onBlur={() => void save()} onKeyDown={(event) => { if (event.key === "Escape") onClose(); if (event.key === "Enter") { event.preventDefault(); void save(); } }} /></div>; }
